name: Database Migrations

on:
  # Run on push to main branch
  push:
    branches: [main]
    paths:
      - 'shared/schema.ts'
      - 'drizzle/**'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run database migrations
        run: npx drizzle-kit push:pg --schema=./shared/schema.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
      # Optional: Add verification step
      - name: Verify migration success
        run: |
          echo "Verifying database schema..."
          npx tsx scripts/verify-schema.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
